-- SQL Queries for Retail Business Analysis
-- Total Records
SELECT COUNT(*) AS TOTAL_RECORDS FROM SUPERSTORE;

-- Total Sales 
SELECT SUM(SALES) AS TOTAL_SALES FROM SUPERSTORE;

-- Total Profit
SELECT SUM(PROFIT) AS TOTAL_PROFIT FROM SUPERSTORE;

-- Sales by Category
SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES FROM SUPERSTORE GROUP BY CATEGORY ORDER BY TOTAL_SALES DESC;

-- Profit by Category
SELECT CATEGORY, SUM(PROFIT) AS TOTAL_PROFIT FROM SUPERSTORE GROUP BY CATEGORY ORDER BY TOTAL_PROFIT DESC;

-- Sales by Region
SELECT REGION, SUM(SALES) AS TOTAL_SALES FROM SUPERSTORE GROUP BY REGION ORDER BY TOTAL_SALES DESC;

-- Profit by Region
SELECT REGION, SUM(PROFIT) AS TOTAL_PROFIT FROM SUPERSTORE GROUP BY REGION ORDER BY TOTAL_PROFIT DESC;

-- Top 10 Customers by Sales
SELECT * FROM (SELECT CUSTOMER_NAME, SUM(SALES) AS TOP_10_CUSTOMER_SALES FROM SUPERSTORE GROUP BY CUSTOMER_NAME ORDER BY SUM(SALES) DESC) WHERE ROWNUM <= 10;

-- Top 10 Products by Profit
SELECT * FROM (SELECT PRODUCT_NAME, SUM(PROFIT) AS TOP_10_PRODUCT_PROFIT FROM SUPERSTORE GROUP BY PRODUCT_NAME ORDER BY SUM(PROFIT) DESC) WHERE ROWNUM <= 10;

-- Monthly Sales Trend
SELECT TO_CHAR(ORDER_DATE,'YYYY-MM') AS MONTH, SUM(SALES) AS TOTAL_SALES_PER_MONTH FROM SUPERSTORE GROUP BY TO_CHAR(ORDER_DATE,'YYYY-MM') ORDER BY MONTH;

-- Discount vs Average Profit
SELECT DISCOUNT, ROUND(AVG(PROFIT),2) AS AVG_PROFIT FROM SUPERSTORE GROUP BY DISCOUNT ORDER BY DISCOUNT;

-- Loss-Making Discount Levels
SELECT DISCOUNT, ROUND(AVG(PROFIT),2) AS AVG_PROFIT FROM SUPERSTORE GROUP BY DISCOUNT HAVING AVG(PROFIT)<0 ORDER BY DISCOUNT;